### PR TITLE
Also test on Python 3.6 and 3.7

### PR DESCRIPTION
**Pull request by inglesp**
Supersedes #28.

### CODE REVIEW

**Comment by inglesp** [comment]
Travis failed to build the first commit on 3.7, with the following error:

```
3.7 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.7.tar.bz2
$ curl -sSf -o python-3.7.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.7 archive. The archive may not exist. Please consider a different version.
```

Googling led me to https://github.com/travis-ci/travis-ci/issues/9815 which in turn led me to https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905, and so I updated this PR with 604cb22532f377d8897b31b49c46fba4b7b8aec0.

However, Travis has failed to build this new commit on 3.4, with the same error (but for 3.4):

```
3.4 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/16.04/x86_64/python-3.4.tar.bz2
$ curl -sSf -o python-3.4.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 403 Forbidden
Unable to download 3.4 archive. The archive may not exist. Please consider a different version.
```

I have re-run the build job a few times, and it always fails in the same way.

But I can download the archive locally (via `curl -sSf -o python-3.4.tar.bz2 https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.4.tar.bz2`) so I've got no idea what's going on!

**Comment by inglesp** [comment]
This is possibly the same issue as https://github.com/travis-ci/travis-ci/issues/9782, but there's no resolution on that issue, and it's been open since June.

**Comment by inglesp** [comment]
I've triggered a completely new build job but that's also failing on 3.4.

I'd guess the problem is at Travis's end, so I'll come back in a day or two and try again.

**Comment by jpadilla** [comment]
@inglesp might be worth checking out if there's anything on django-rest-framework's setup we can use...

https://github.com/encode/django-rest-framework/blob/master/.travis.yml

**Comment by inglesp** [comment]
This now passes on on 3.4, so as I'd guessed, the problem must've been on Travis's end.

**Comment by inglesp** [comment]
@jpadilla Please could you review and merge?

**Comment by jpadilla** [comment]
@inglesp great stuff, thanks!

**Pull request merged**
